### ISSUE TITLE
To Do - The Daily Check

### ISSUE THREAD

**Issue by ZakaHaceCosas** [ZakaHaceCosas/personaplus#10]
# The "Daily Check"

> [!TIP]
> **What is it**: Formerly called "Think Hour", it's an hour of the day where a notification is sent for the user to reflect on his day. You get to fill in a simple form asking you about what you've done, how you've slept, if you've accomplished your passive objectives for today, among other aspects relevant to your daily wellbeing.

### To Do:
- [ ] Implementation
  - [ ] Daily notification
  - [ ] Form itself
    - [ ] Section for registering sleep hours of the previous night
    - [ ] Section for registering what's been eaten
    - [ ] Section for registering accomplishment of passive objectives[^1]
  - [ ] Customizing the form (enabling or disabling certain fields depending on the user)
- [ ] Passive objective integration[^1]
- [ ] Data registering
  - [ ] Data saving
  - [ ] Visualizing personal graphs (TODO: elaborate this idea...)

[^1]: Also see [Passive objectives](https://github.com/users/ZakaHaceCosas/projects/1/views/1?pane=issue&itemId=75052042)

**Comment by ZakaHaceCosas** [comment]
We've rethought the app and will reorganize our ROADMAP. Closing all tracking issues for now.
