### ISSUE TITLE
R6 plans

### ISSUE THREAD

**Issue by ZakaHaceCosas** [ZakaHaceCosas/personaplus#11]
> [!NOTE]
> :es: A partir de ahora, el repositorio está en proceso de migrar por completo a **inglés**.

# Plans for the R6 rewrite
(hopefully) The last time I'll need to deeply restructure my project before a release.
---

Hi there!

I'll go straight to the point, this is the list of goals I want to achieve before considering R6 production ready, so we can finally merge this with `main` and get another PRE-APP release.

- [X] Getting the basic features from R5 to work (creating active objectives, removing them, etc...).

> [!IMPORTANT]
> (05/12/2024) **UPDATE:** I finally got all R5 features re-implemented! Just two days before PersonaPlus' birthday btw.

Actually, just that would be enough to merge. But here are some extra goals I will try to achieve:

- [X] Make the on-boarding experience better. **Done.**
- [X] Make the daily log functional, at least show a simple calendar on your home page. **Done (table on the homepage. It will be done better in the future).**
- [X] Fix all known errors. See #3 for more info.
- [X] Improve the UI to be better and actually follow my original design.
  - [X] Add icons to objectives at the dashboard. (DONE, UNCOMMITTED)
  - [X] Ensure consistent sizing, measurement, and so on. **Done.**
  - [X] Reorganize the Profile page and create a settings page to separate stuff. **Done.**
  - [X] Other changes...
- [X] ~~Add the ability to edit an active objective.~~ (EDIT: It will be added, but not for now).
- [X] Add the ability to view some pieces of data (e.g. BFP or BMI) and what they should mean to the user, via CoreLibrary (formerly "OpenHealth"). **Done (Report page).**
- [X] ~~Add a light theme (yes)~~. (EDIT: It will be added, but not for now).

I will achieve them anyways, either before or after the R6 "completion", but I'll try to make the merged result as cool as possible. If I see it's taking too long to do all of this I'll just merge and keep going from the `main` branch and with the typical 1-2 week PRE-APP release cycle.

Until then, see ya!

*Edit (5 Sep 2024)*:

***Final tasks for release:***

- [X] Fix version (from 0.0.26-preapp.6 to 0.0.6-preapp.26) (DONE)
- [X] Re-add update check from inside the app (DONE, UNCOMMITTED)
- [X] (Attempt at least) Fix CoreLibrary calculations ~~& add calculations for newly added objectives~~. (_new types of objectives will come after R6_) (DONE)
- [X] (Attempt at least) Bring back notification reminders (DONE)
  - [X] Optionally, allow to opt-out from them via the new settings.

**Comment by ZakaHaceCosas** [comment]
An update into this, all R5 features are finally working on Expo Go as intended, EAS builds have been fixed and the Android bundle is also working (almost) flawlessly! A few fixes are needed but most stuff is up and running. I'll try to implement the UI changes, editing active objectives, and take care of the finishing touches (translation, TODOs, etc...) between today and tomorrow.

**Mark 7th December (PersonaPlus 1st birthday!) as the R6 release date if everything goes well!**

**Comment by ZakaHaceCosas** [comment]
Done.
