### ISSUE TITLE
To Do - Active Objectives

### ISSUE THREAD

**Issue by ZakaHaceCosas** [ZakaHaceCosas/personaplus#5]
# Active objectives

> [!TIP]
> **What they are:** Think of apps like [Leap Home Workout](https://play.google.com/store/apps/details?id=homeworkout.homeworkouts.noequipment), where you can start physical exercising sessions, being the app an "assistant" that helps you during the process. Well, that thing is called an "active objective" in PersonaPlus.

### To Do:
- [X] Creation
- [ ] Sessions
  - [X] Basic functionality
    - [X] Timer
    - [X] Rests
    - [X] Finishing
      - [X] Give up
  - [ ] Advanced functionality
    - [X] Basic help (a text wall, lol)
    - [ ] Quality help (with images and context-aware info (like not giving the same advice to a 13 year old user than to a 57 year old one)
    - [ ] Full sessions
      - [ ] Obtaining data
        - [X] Measure burnt calories [^1]
        - [ ] Measure specific data (eg. total kilometers of a running session)
      - [X] Data saving
      - [X] Stats / insights [^1]
    - [ ] Trivial features
      - [ ] A music player (music built in to the app)
      - [ ] Sound effects [^2]
      - [ ] Chained sessions / Micro sessions [^3]
- [X] Editing
- [X] Removing
- [ ] Having an assistant to create them [^4]

[^1]: By [CoreLibrary](https://github.com/ZakaHaceCosas/personaplus/blob/main/core/README.md)
[^2]: Important, as you might not be looking at your phone while doing stuff.
[^3]: The app I used as an example before (Leap) works in a different way than ours, where each session is a lot of "micro" exercises of usually no more than 30 seconds, unlike PersonaPlus where an active objective is a single exercise that can last from a few seconds to more than an hour. The long term idea is to be able to choose between _macro_ sessions (current ones) and _micro_ sessions (the ones I just described) - being _micro_ sessions "chained" sessions of different short-duration  exercises.
[^4]: Assistant **!=** AI.

**Comment by ZakaHaceCosas** [comment]
We've rethought the app and will reorganize our ROADMAP. Closing all tracking issues for now.
