### ISSUE TITLE
To Do - Users & database

### ISSUE THREAD

**Issue by ZakaHaceCosas** [ZakaHaceCosas/personaplus#6]
# User registering

> [!TIP]
> **What is it:** The ability for users to enter data in the app so they can have the best experience with the app.

### To do:
- [ ] Registering users
  - [X] Basic data (age, height, weight...)
  - [ ] App personalization
    - [X] Goals [^1]
    - [X] Medical info [^2]
    - [ ] Others
  - [X] Check Time [^1]
- [ ] Users and database
  - [X] Generating a report [^3]
  - [ ] Giving them recommendations
  - [X] Edit profile
  - [X] Remove account ("Reset app" inside the app)
  - [X] Backup data [^4]

[^1]: It's purely visual, actual functionality is not (YET) implemented.
[^2]: This is basically to, for example, avoid recommending active objectives like running to users with breathing problems.
[^3]: Work in progress, hidden behind an experiment.
[^4]: It's more likely to end up being "export to file" rather than a cloud account system.

**Comment by ZakaHaceCosas** [comment]
We've rethought the app and will reorganize our ROADMAP. Closing all tracking issues for now.
