### ISSUE TITLE
To Do - Misc

### ISSUE THREAD

**Issue by ZakaHaceCosas** [ZakaHaceCosas/personaplus#7]
# Miscellaneous

> [!TIP]
> **What is it:** Various extra details, that aren't as important but help the app feel more polished. They aren't separated into categories. As with everything else, I'm open to suggestions.

- [ ] Misc
  - [ ] App themes.
    - [ ] Basic dark / light
    - [ ] More themes maybe?
  - [X] Multiple languages.
    - [X] Spanish
    - [X] English
  - [ ] Easter eggs.
  - [X] (Our own) sounds effects.
  - [ ] UI animations.

**Comment by ZakaHaceCosas** [comment]
We've rethought the app and will reorganize our ROADMAP. Closing all tracking issues for now.
